# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5483acb1e3387ce90ba50a1c72411788"
name = "first-lazer-app"
application_url = "https://tract-ordinance-circulation-them.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "nate-ce.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,write_discounts,write_pixels,write_products"

[auth]
redirect_urls = [
  "https://tract-ordinance-circulation-them.trycloudflare.com/auth/callback",
  "https://tract-ordinance-circulation-them.trycloudflare.com/auth/shopify/callback",
  "https://tract-ordinance-circulation-them.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
